app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('core.api.urls')),
    path('', include('page.urls')),
    path('accounts/', include('allauth.urls')),
    path('groups/', include('groups.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path(
        '',
        views.GroupListView.as_view(),
        name='group_page'),
    path(
        'create/',
        views.GroupCreateView.as_view(),
        name='group_create'
        ),
    path(
        '<slug>/',
        views.GroupDetailView.as_view(),
        name='group_detail'
        ),
    path(
        '<slug>/add-post',
        views.group_create_post,
        name='group_post_create'
        ),
    path(
        '<slug>/join',
        views.GroupJoinView.as_view(),
        name='group_join'
        ),
    path(
        '<slug>/leave',
        views.GroupLeaveView.as_view(),
        name='group_leave'
        ),
    path(
        '<slug>/delete',
        views.GroupDeleteView.as_view(),
        name='group_delete'),
    path(
        'post/<int:pk>/delete/',
        views.PostDeleteView.as_view(),
        name='post_delete'
        ),
    path(
        'post/<int:pk>/update',
        views.PostEditView.as_view(),
        name='post_edit',
    )
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path(
        '',
        views.homeview,
        name='home_page'),
    path(
        'resources/',
        views.ResourcePage.as_view(),
        name='resources_page'),
    path(
        'blog/',
        views.BlogPage.as_view(),
        name='blog_page'),
    path(
        'blog/<slug>/',
        views.BlogDetailView.as_view(),
        name='blog_detail'
        ),
    path(
        'blog/create',
        views.BlogCreateView.as_view(),
        name='blog_create'
        ),
    path(
        'blog/<slug>/update',
        views.BlogEditView.as_view(),
        name='blog_edit'
        ),
    path(
        'blog/<slug>/delete',
        views.BlogDeleteView.as_view(),
        name='blog_delete'
        ),
    path(
        '<str:slug>',
        views.ProfileView.as_view(),
        name='profile_view'
    ),
    path(
        '<str:slug>/edit',
        views.ProfileEdit.as_view(),
        name='profile_edit',
    ),
    path(
        'topic/<str:slug>',
        views.filterview,
        name='topic'
    )

]

groups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse


User = get_user_model()

group_status = [
    ('Public', 'Public'),
    ('Private', 'Private'),
    ('Close', 'Close'),
]


class Group(models.Model):
    title = models.CharField(max_length=99)
    admin = models.ManyToManyField(User, related_name='admin')
    data_created = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=656)
    members = models.ManyToManyField(User, related_name='members')
    cover = models.ImageField(blank=True, upload_to='group_cover/')
    slug = models.SlugField(unique=True)
    status = models.CharField(max_length=50, choices=group_status)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:group_detail", kwargs={'slug': self.slug})


category_choices = [
    ('django', 'django'),
    ('react', 'react'),
    ('laravel', 'lavarel'),
    ('angular', 'angular'),
]


class Category(models.Model):
    name = models.CharField(max_length=20, choices=category_choices)
    slug = models.SlugField()

    def save(self, name, *args, **kwargs):
        self.slug = slugify(self.name)
        self.anem = name
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class GroupPost(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='group_posts'
        )

    groups = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name='post'
        )
    body = models.CharField(max_length=256, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    categories = models.ForeignKey(
        Category, on_delete=models.CASCADE,
        null=True,
        )

    def get_absolute_url(self):
        return reverse(
            "groups:group_detail",
            kwargs={'slug': self.groups.slug}
            )

groups/forms.py
from django import forms
from . import models


class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = models.Group
        fields = ['id', 'title', 'description', 'status', ]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }


class GroupPostForm(forms.ModelForm):

    class Meta:
        model = models.GroupPost
        fields = ['body', 'categories']

        widgets = {
            'body': forms.TextInput(attrs={'class': 'form-control'}),
            'categories': forms.Select(attrs={'class': 'form-control'})

        }

groups/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import (CreateView, DetailView,
                                  ListView, RedirectView,
                                  DeleteView, UpdateView
                                  )

from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from . import forms
from django.contrib.auth.decorators import login_required
# Create your views here.


class GroupCreateView(LoginRequiredMixin, CreateView):
    """ Creating new group """

    model = models.Group
    template_name = 'group_create.html'
    form_class = forms.GroupCreateForm

    def form_valid(self, form):
        form.save()
        form.instance.admin.add(self.request.user)
        form.instance.members.add(self.request.user)
        form.save()

        return super().form_valid(form)


class GroupDetailView(LoginRequiredMixin, DetailView):

    """ Group details and Post """
    model = models.Group
    template_name = 'group_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["categories"] = models.Category.objects.all()
        return context


class GroupListView(ListView,):
    """ Listing available groups """

    model = models.Group
    context_object_name = 'groups'
    template_name = 'group_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["categories"] = models.Category.objects.all()
        return context


class GroupJoinView(LoginRequiredMixin, RedirectView):
    """ View for leaving a group and reversing the templated on join group"""

    def get_redirect_url(self, *args, **kwargs):

        return reverse(
            'groups:group_detail',
            kwargs={'slug': self.kwargs.get('slug')}
            )

    def get(self, request, *args, **kwargs):

        group = get_object_or_404(
                models.Group,
                slug=self.kwargs.get('slug')
                )
        group.members.add(self.request.user)

        return super().get(request, *args, **kwargs)


class GroupLeaveView(LoginRequiredMixin, RedirectView):

    """ View for leaving a group"""

    def get_redirect_url(self, *args, **kwargs):
        return reverse(
            'groups:group_detail',
            kwargs={'slug': self.kwargs.get('slug')}
            )

    def get(self, request, *args, **kwargs):

        group = get_object_or_404(models.Group, slug=self.kwargs.get('slug'))
        group.members.remove(self.request.user)

        return super().get(request, *args, **kwargs)


@login_required
def group_create_post(request, slug, **kwargs):

    group = get_object_or_404(models.Group, slug=slug)
    category = request.POST['category']

    if request.method == 'POST' and category != 'category...':
        
        model = models.GroupPost()
        model.groups = group
        model.user = request.user

        model.save()
        model.body = request.POST['post-text']
        model.categories = models.Category.objects.get(name=request.POST['category'])
        model.save()

        return HttpResponseRedirect(
            reverse('groups:group_detail', kwargs={'slug': group.slug})
            )
    else:
        return HttpResponseRedirect(
            reverse('groups:group_detail', kwargs={'slug': group.slug})
            )



class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Group
    template_name = 'group_delete.html'
    success_url = reverse_lazy('groups:group_page')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = models.GroupPost
    template_name = 'post_delete.html'
    success_url = reverse_lazy('groups:group_page')


class PostEditView(LoginRequiredMixin, UpdateView):
    model = models.GroupPost
    template_name = 'post_edit.html'
    form_class = forms.GroupPostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["categories"] = models.Category.objects.all()
        return context

groups/templates/group_create.html
{% extends 'base.html' %}


{% block body_block %}
    
    <div class="mt-5">
    {% if user.is_authenticated %}
    <h2 class='mb-5'>
        Create new group
        <small class="text-muted h6">Be sure to fill in the blanks</small>
      </h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class='btn btn-primary' type="submit" value="Submit">
    </form>
        
        
    {% endif %}
    </div>

{% endblock body_block %}
    

groups/templates/group_delete.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-info' type="submit">Delete</button>
</form>
    
{% endblock body_block %}

groups/templates/group_detail.html
{% extends 'base.html' %}


{% block body_block %}
<br>
<a class="mt-5" href="{% url 'groups:group_page' %}">Back>></a>
<div class="card mb-3">
  
  {% if group.cover %}
  <img class="card-img-top" src="{{ group.cover.url }}" alt="Card image cap">  
  {% endif %}
    
    <div class="card-body">
      
    
        
      <h1 class="card-title">{{group.title}}</h1>
      <p class="card-text">{{group.description}}</p>
      <p class="card-text"><small class="text-muted">{{group.data_created}}</small></p>

      

        
      
        
      {% if user in group.members.all %}

      <a class="btn btn-danger " href="{% url 'groups:group_leave' slug=group.slug %}">Leave Group</a>
        
      {% else %}  
      
      <a class="btn btn-primary " href="{% url 'groups:group_join' slug=group.slug %}">Join Group</a>
        
      {% endif %}

      {% if user in group.admin.all %}

      <a class="btn btn-warning " href="{% url 'groups:group_delete' slug=group.slug  %}">Delete Group</a>
    {% endif %}
    </div>
  </div>
  
  

    

    

  {% if user in group.members.all %}
  
  <form  action="{% url 'groups:group_post_create' slug=group.slug %}" method="POST">
    <h2 class=''>
      Create new post
      <small class="text-muted h6">Be sure to fill in the blanks</small>
    </h2>
    {{ user.username }}
    {% csrf_token %}
    <textarea class="form-control" name="post-text" id="" cols="30" rows="10" style="resize: none;" placeholder="Whats on your mind?"></textarea><br>
    <select  name="category" class="form-select form-control" aria-label="Default select example">
      <option selected value="category...">Category</option>
      <option value="django">Django</option>
      <option value="react">React</option>
      <option value="lavarel">Laravel</option>
      <option value="angular">Angular</option>
      
    </select>

    <input class='btn btn-primary mt-3' type="submit" value="Submit" >
</form>
  
 
 {% for post in group.post.all %}

 

 <div class="card mt-3">
  <div class="card-header">
    <a href="{% url 'page:profile_view' slug=user.profile.slug %}">@{{post.user.username}}</a>
    {% if user == post.user or user in group.admin.all %}
    <a href="{% url 'groups:post_edit' pk=post.pk %}" class="btn btn-info float-right ml-2">Edit</a>
    <a href="{% url 'groups:post_delete' pk=post.pk %}" class="btn btn-warning float-right">Delete</a>
    {% endif %}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{post.date_created}}</h5>
    <p class="card-text">{{post.body|safe}}</p>
    
    
      
    
  </div>
</div>
 
   
 {% endfor %}
   
  

  {% else %}

  <h2 class="text-center">Please join the group first</h2>
  

  

{% endif %}


    

    
{% endblock body_block %}
    

groups/templates/group_list.html
{% extends 'base.html' %}


{% block body_block %}
<div class="mt-5">

{% if user.is_authenticated %}

<a class="btn btn-info" href="{% url 'groups:group_create' %}">New Group+</a>
  
{% endif %}
  

<ul class="list-unstyled">
{% for group in groups %}

<li>
        <div class="mt-4">
        <div class="card" style="width: auto;">
            <div class="card-body">
              <h5 class="card-title">{{group.title}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ group.data_created|date:"d M, Y" }}</h6>
              <p class="card-text">{{ group.description }}</p>
              
              {% if user not in group.members.all %}
              <a href="{% url 'groups:group_join' slug=group.slug %}" class="btn btn-success">Join</a>
              
              
              {% endif %}
              <a href="{% url 'groups:group_detail' slug=group.slug %}" class="btn btn-info">View Group</a>
                
              
            </div>
          </div>
        </div>
        

</li>

    
{% endfor %}
</ul>
</div>

{% endblock body_block %}

groups/templates/post_delete.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-info' type="submit">Delete</button>
</form>
    
{% endblock body_block %}

groups/templates/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {{ user.username }}
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-info' type="submit">Update</button>
</form>
    
{% endblock body_block %}