app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('core.api.urls')),
    path('', include('page.urls')),
    path('accounts/', include('allauth.urls')),
    path('groups/', include('groups.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path(
        '',
        views.GroupListView.as_view(),
        name='group_page'),
    path(
        'create/',
        views.GroupCreateView.as_view(),
        name='group_create'
        ),
    path(
        '<slug>/',
        views.GroupDetailView.as_view(),
        name='group_detail'
        ),
    path(
        '<slug>/add-post',
        views.group_create_post,
        name='group_post_create'
        ),
    path(
        '<slug>/join',
        views.GroupJoinView.as_view(),
        name='group_join'
        ),
    path(
        '<slug>/leave',
        views.GroupLeaveView.as_view(),
        name='group_leave'
        ),
    path(
        '<slug>/delete',
        views.GroupDeleteView.as_view(),
        name='group_delete'),
    path(
        'post/<int:pk>/delete/',
        views.PostDeleteView.as_view(),
        name='post_delete'
        ),
    path(
        'post/<int:pk>/update',
        views.PostEditView.as_view(),
        name='post_edit',
    )
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path(
        '',
        views.homeview,
        name='home_page'),
    path(
        'resources/',
        views.ResourcePage.as_view(),
        name='resources_page'),
    path(
        'blog/',
        views.BlogPage.as_view(),
        name='blog_page'),
    path(
        'blog/<slug>/',
        views.BlogDetailView.as_view(),
        name='blog_detail'
        ),
    path(
        'blog/create',
        views.BlogCreateView.as_view(),
        name='blog_create'
        ),
    path(
        'blog/<slug>/update',
        views.BlogEditView.as_view(),
        name='blog_edit'
        ),
    path(
        'blog/<slug>/delete',
        views.BlogDeleteView.as_view(),
        name='blog_delete'
        ),
    path(
        '<str:slug>',
        views.ProfileView.as_view(),
        name='profile_view'
    ),
    path(
        '<str:slug>/edit',
        views.ProfileEdit.as_view(),
        name='profile_edit',
    ),
    path(
        'topic/<str:slug>',
        views.filterview,
        name='topic'
    )

]

page/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
</head>
<body>

    
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        <a id='navbrand' class="navbar-brand" href="{% url 'page:home_page' %}">
          <img src="{% static 'images/base/icon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          IT Community
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul  class="navbar-nav mr-auto pl-5">

              <li class="nav-item pl-5">
                <a id='navbar' class="nav-link" href="{% url 'groups:group_page' %}">Groups</a>
              </li>
              <li class="nav-item dropdown pl-5">
                

                <a id='navbar' class="nav-link dropdown-toggle"href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hot Topics</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          
                  {% for cat in categories %}
                   
                  <a class="dropdown-item" href="{% url 'page:topic' slug=cat.slug%}"><option value="{{cat}}">{{cat|title}}</option></a>
                  {% endfor %}
           
                    
                  
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">View all Hot Topics</a>
                  
                </div>
           
              </li>
              <li class="nav-item pl-5">
                <a id='navbar' class="nav-link" href="{% url 'page:resources_page' %}">Resources</a>
              </li>
              <li class="nav-item pl-5">
                <a id='navbar' class="nav-link" href="{% url 'page:blog_page' %}">Blog</a>
              </li>
            </ul>
            

            <ul class="navbar-nav mr-right ">
                
                {% if user.is_authenticated %}

                <li class="nav-item">
                  <a id='navbar' class="nav-link" href="{% url 'page:profile_view' slug=user.profile.slug %}">{{user.username}}</a>
                </li>
                <li class="nav-item">
                  <a id='navbar' class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                </li>

                {% else %}
              <li class="nav-item">
                  <a id='navbar' class="nav-link" href="{% url   'account_login' %}">Log In</a>
                </li>
              <li class="nav-item pl-3">
                  <a  id='navbar' class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
              </li>                  
                {% endif %}
                  

            </ul>

        </div>
    </nav>
    
    <div class="container">
    {% block body_block %}
        
    {% endblock body_block %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

page/templates/blog.html
{% extends 'base.html' %}


{% block body_block %}
<h1 class="text-center mt-5">IT community blog</h1>
<div class="mt-5">
  {% if user.is_superuser or user.is_staff%}
  <a class="text-right btn btn-primary mb-2" href="{% url 'page:blog_create' %}">Create New Blog+</a>
    
  {% endif %}
<div class="row mt-3">
{% for blog in blogs %}


<div class="card ml-5 mt-5" style="width: 18rem;">
    <img class="card-img-top" src="{{ blog.thumbnail.url }}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">{{blog.title}}</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="{% url 'page:blog_detail' slug=blog.slug %}" class="">Read More >></a>
    </div>
  </div>

{% endfor %}
</div>
</div>



  

    
{% endblock body_block %}
    

page/templates/blog_create.html
{% extends 'base.html' %}
{% load static %}


{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media}}
    {{ form.as_p }}
    <button class='btn btn-info' type="submit">Create Blog</button>
</form>
    
{% endblock body_block %}
    

page/templates/blog_delete.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-info' type="submit">Delete</button>
</form>
    
{% endblock body_block %}

page/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
<link rel="stylesheet" href="{% static '/css/blog_detail.css' %}">
    <div class="card mt-5 mb-5" >
        <div class="card-body">    
          {% if blog.images %}
          <img src="{{blog.images.url}}" class="img-fluid" alt="Responsive image">
          {% endif %}
         
          
          <h5 class="card-title">{{blog.title}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
          <p class="card-text img-fluid">{{blog.body|safe}}</p>
          <p class="text-left">{{blog.author}}<br>{{blog.date_created}}</p>
          
          
          
          {% if user.is_superuser or user.is_staff%}
          <a class="text-right btn btn-info" href="{% url 'page:blog_edit' slug=blog.slug %}">Edit</a>
          <a class="btn btn-danger" href="{% url 'page:blog_delete' slug=blog.slug %}" class="card-link">Delete</a>
            
          {% endif %}
        </div>

      </div>
  
        

{% endblock body_block %}
      

page/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block body_block %}
<link rel="stylesheet" href="{% static '/css/index.css' %}">
<title>IT Community</title>



{% if user.is_authenticated %}
<div id="header">
    <h1>Pota</h1>
    </div>
    
        <h1>ews</h1>
{% else %}
    
{% endif %}
    

{% endblock body_block %}
    

page/templates/profile.html
{% extends 'base.html' %}
{% load static %}


{% block body_block %}
<link rel="stylesheet" href="{% static '/css/profile.css' %}">
<div class="body">



<div class="row mt-5">
<div class="col-md-12">

  <div class="card mb-3">
    <img class="card-img-top" src="{{user.profile.cover.url}}" alt="Card image cap">
    <div class="card-body">
      <img  id="profile" class="rounded-circle" src="{{user.profile.image.url}}">
      <h5 class="card-title text-center">{{user.first_name}} {{user.last_name}} <br><a href="{% url 'page:profile_view' slug=user.profile.slug %}"><small>@{{user.username}}</small></a></h5>
      <p class="card-text text-center">{{user.profile.bio}}</p>
      <a  class="d-flex justify-content-center" href="{% url 'page:profile_edit' slug=user.profile.slug %}">Edit+</a>
    </div>
  </div>
  
  
  
  

</div>

<div class="col-md-12" ">
{% for post in posts.all %}


  
  {% if user == post.user or user in post.admin.all %}

      
  <div class="card mt-3 mb-3">
    <div class="card-header">
      <a href="{% url 'page:profile_view' slug=user.profile.slug %}">@{{post.user.username}}</a>
   
      <a href="{% url 'groups:post_edit' pk=post.pk %}" class="btn btn-info float-right ml-2">Edit</a>
      <a href="{% url 'groups:post_delete' pk=post.pk %}" class="btn btn-warning float-right">Delete</a>
 
    </div>
    <div class="card-body">
      <h5 class="card-title">{{post.date_created}}</h5>
      <p class="card-text">{{post.body|safe}}</p>
    


      
      
        
      
    </div>
  </div>
  {% endif %}
  
{% endfor %}
  

</div>





</div>
</div>
{% endblock body_block %}
    

page/templates/profile_update.html
{% extends 'base.html' %}
{% load static %}


{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
    
{% endblock body_block %}
    

page/templates/topics.html
{% extends 'base.html' %}
{% load static %}


{% block body_block %}

<div class="jumbotron mt-5">
  <div class="container">
    <h1 class="display-4 text-center">{{queryset.0.categories|title}}</h1>
  </div>
</div>

{% for qs in queryset %}

<div class="card mt-3 mb-3">
    <div class="card-header">
      <a href="{% url 'page:profile_view' slug=user.profile.slug %}">@{{qs.user.username}}</a>
   
      <a href="{% url 'groups:post_edit' pk=qs.pk %}" class="btn btn-info float-right ml-2">Edit</a>
      <a href="{% url 'groups:post_delete' pk=qs.pk %}" class="btn btn-warning float-right">Delete</a>
 
    </div>
    <div class="card-body">
      <h5 class="card-title">{{qs.date_created}}</h5>
      <p class="card-text">{{qs.body|safe}}</p>

    </div>
</div>
    
{% endfor %}
    
{% endblock body_block %}
    